version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - echo Starting build...
      - echo Login to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPO_URL_API=276704211106.dkr.ecr.eu-west-1.amazonaws.com/api
      - REPO_URL_WEB=276704211106.dkr.ecr.eu-west-1.amazonaws.com/web
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_NUMBER | awk -F":" '{print $2}')
  build:
    commands:
      - echo Building image `date`
      - docker build -t $REPO_URL_API:latest ./words
      - docker build -t $REPO_URL_WEB:latest ./web
      - echo Taging image with build number $CODEBUILD_BUILD_NUMBER
      - docker tag $REPO_URL_API:latest $REPO_URL_API:$COMMIT_HASH
      - docker tag $REPO_URL_WEB:latest $REPO_URL_WEB:$COMMIT_HASH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to $REPO_URL
      - docker push $REPO_URL_API:latest
      - docker push $REPO_URL_WEB:latest #<-- latest umjesto codebuild-numbera
      - docker push $REPO_URL_API:$COMMIT_HASH
      - docker push $REPO_URL_WEB:$COMMIT_HASH
      - echo Image pushed on `date`
      - printf '[{"name":"api","imageUri":"%s"}]' $REPO_URL_API:$COMMIT_HASH > imageDetail.json
      - printf '[{"name":"web","imageUri":"%s"}]' $REPO_URL_WEB:$COMMIT_HASH > imageDetail.json
      - cat imageDetail.json
      - echo Done
# i ovo novo dole
artifacts:
  files:
    - 'appspec.yaml'
    - 'taskdef.json'
    - 'imageDetail.json'
#